name: Run CI

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.5'
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Black
        uses: microsoft/action-python@0.7.0
        with:
          black: true

      - name: Pylint
        uses: microsoft/action-python@0.7.0
        with:
          pylint: true
